/* big_100.sas — generated by testdata/gen_big.py for Bench performance tests */
libname sales 'C:\SASData\Sales';

data sales.sales_data;
input sale_id $ sale_amount date :mmddyy10.;
format date mmddyy10.;
datalines;
001 50 02/02/2023
002 130 03/03/2023
003 130 04/04/2023
004 300 05/05/2023
005 50 06/06/2023
006 199 07/07/2023
007 130 08/08/2023
008 199 09/09/2023
009 75 10/10/2023
010 130 11/11/2023
011 150 12/12/2023
012 300 01/13/2023
013 0 02/14/2023
014 150 03/15/2023
015 0 04/16/2023
016 0 05/17/2023
017 199 06/18/2023
018 130 07/19/2023
019 75 08/20/2023
020 0 09/21/2023
021 199 10/22/2023
022 199 11/23/2023
;
run;

PROC SQL;
CREATE TABLE sales.t0001 AS
SELECT SUM(sale_amount) AS total_sales FROM sales.sales_data;
run;

PROC SQL;
CREATE TABLE sales.t0002 AS
SELECT AVG(sale_amount) AS avg_sales FROM sales.t0001;
run;

PROC SQL;
CREATE TABLE sales.t0003 AS
SELECT MONTH(DATE) AS sale_month, SUM(sale_amount) AS total_monthly_sales FROM sales.sales_data GROUP BY MONTH(DATE);
run;

PROC SQL;
CREATE TABLE sales.t0004 AS
SELECT * FROM sales.t0002 WHERE sale_amount > (SELECT avg_sales FROM sales.t0001);
run;

data sales.t0005;
	merge sales.t0001(in=a) sales.t0001(in=b);
by sale_month;
run;

data sales.t0006;
	set sales.t0001;
	if sale_amount > 100;
run;

PROC SQL;
CREATE TABLE sales.t0007 AS
SELECT SUM(sale_amount) AS total_sales FROM sales.t0002;
run;

PROC SQL;
CREATE TABLE sales.t0008 AS
SELECT AVG(sale_amount) AS avg_sales FROM sales.t0006;
run;

PROC SQL;
CREATE TABLE sales.t0009 AS
SELECT MONTH(DATE) AS sale_month, SUM(sale_amount) AS total_monthly_sales FROM sales.t0003 GROUP BY MONTH(DATE);
run;

PROC SQL;
CREATE TABLE sales.t0010 AS
SELECT * FROM sales.t0006 WHERE sale_amount > (SELECT avg_sales FROM sales.t0007);
run;

proc print data=sales.t0010; title 't0010'; run;

data sales.t0011;
	merge sales.t0008(in=a) sales.t0004(in=b);
by sale_month;
run;

data sales.t0012;
	set sales.t0006;
	if sale_amount > 50;
run;

PROC SQL;
CREATE TABLE sales.t0013 AS
SELECT SUM(sale_amount) AS total_sales FROM sales.t0010;
run;

PROC SQL;
CREATE TABLE sales.t0014 AS
SELECT AVG(sale_amount) AS avg_sales FROM sales.t0010;
run;

PROC SQL;
CREATE TABLE sales.t0015 AS
SELECT MONTH(DATE) AS sale_month, SUM(sale_amount) AS total_monthly_sales FROM sales.t0001 GROUP BY MONTH(DATE);
run;

PROC SQL;
CREATE TABLE sales.t0016 AS
SELECT * FROM sales.t0005 WHERE sale_amount > (SELECT avg_sales FROM sales.sales_data);
run;

data sales.t0017;
	merge sales.t0012(in=a) sales.t0004(in=b);
by sale_month;
run;

data sales.t0018;
	set sales.t0005;
	if sale_amount > 50;
run;

PROC SQL;
CREATE TABLE sales.t0019 AS
SELECT SUM(sale_amount) AS total_sales FROM sales.t0005;
run;

PROC SQL;
CREATE TABLE sales.t0020 AS
SELECT AVG(sale_amount) AS avg_sales FROM sales.sales_data;
run;

proc print data=sales.t0020; title 't0020'; run;

PROC SQL;
CREATE TABLE sales.t0021 AS
SELECT MONTH(DATE) AS sale_month, SUM(sale_amount) AS total_monthly_sales FROM sales.t0007 GROUP BY MONTH(DATE);
run;

PROC SQL;
CREATE TABLE sales.t0022 AS
SELECT * FROM sales.t0014 WHERE sale_amount > (SELECT avg_sales FROM sales.t0020);
run;

data sales.t0023;
	merge sales.t0012(in=a) sales.t0004(in=b);
by sale_month;
run;

data sales.t0024;
	set sales.t0019;
	if sale_amount > 150;
run;

PROC SQL;
CREATE TABLE sales.t0025 AS
SELECT SUM(sale_amount) AS total_sales FROM sales.t0024;
run;

PROC SQL;
CREATE TABLE sales.t0026 AS
SELECT AVG(sale_amount) AS avg_sales FROM sales.t0001;
run;

PROC SQL;
CREATE TABLE sales.t0027 AS
SELECT MONTH(DATE) AS sale_month, SUM(sale_amount) AS total_monthly_sales FROM sales.t0019 GROUP BY MONTH(DATE);
run;

PROC SQL;
CREATE TABLE sales.t0028 AS
SELECT * FROM sales.t0007 WHERE sale_amount > (SELECT avg_sales FROM sales.t0022);
run;

data sales.t0029;
	merge sales.t0019(in=a) sales.t0024(in=b);
by sale_month;
run;

data sales.t0030;
	set sales.t0029;
	if sale_amount > 150;
run;

proc print data=sales.t0030; title 't0030'; run;

PROC SQL;
CREATE TABLE sales.t0031 AS
SELECT SUM(sale_amount) AS total_sales FROM sales.t0022;
run;

PROC SQL;
CREATE TABLE sales.t0032 AS
SELECT AVG(sale_amount) AS avg_sales FROM sales.t0018;
run;

PROC SQL;
CREATE TABLE sales.t0033 AS
SELECT MONTH(DATE) AS sale_month, SUM(sale_amount) AS total_monthly_sales FROM sales.t0021 GROUP BY MONTH(DATE);
run;

PROC SQL;
CREATE TABLE sales.t0034 AS
SELECT * FROM sales.t0033 WHERE sale_amount > (SELECT avg_sales FROM sales.t0021);
run;

data sales.t0035;
	merge sales.t0034(in=a) sales.t0023(in=b);
by sale_month;
run;

data sales.t0036;
	set sales.t0030;
	if sale_amount > 100;
run;

PROC SQL;
CREATE TABLE sales.t0037 AS
SELECT SUM(sale_amount) AS total_sales FROM sales.t0003;
run;

PROC SQL;
CREATE TABLE sales.t0038 AS
SELECT AVG(sale_amount) AS avg_sales FROM sales.t0006;
run;

PROC SQL;
CREATE TABLE sales.t0039 AS
SELECT MONTH(DATE) AS sale_month, SUM(sale_amount) AS total_monthly_sales FROM sales.t0019 GROUP BY MONTH(DATE);
run;

PROC SQL;
CREATE TABLE sales.t0040 AS
SELECT * FROM sales.t0027 WHERE sale_amount > (SELECT avg_sales FROM sales.t0016);
run;

proc print data=sales.t0040; title 't0040'; run;

data sales.t0041;
	merge sales.t0016(in=a) sales.t0028(in=b);
by sale_month;
run;

data sales.t0042;
	set sales.t0034;
	if sale_amount > 100;
run;

PROC SQL;
CREATE TABLE sales.t0043 AS
SELECT SUM(sale_amount) AS total_sales FROM sales.t0040;
run;

PROC SQL;
CREATE TABLE sales.t0044 AS
SELECT AVG(sale_amount) AS avg_sales FROM sales.t0020;
run;

PROC SQL;
CREATE TABLE sales.t0045 AS
SELECT MONTH(DATE) AS sale_month, SUM(sale_amount) AS total_monthly_sales FROM sales.t0014 GROUP BY MONTH(DATE);
run;

PROC SQL;
CREATE TABLE sales.t0046 AS
SELECT * FROM sales.t0009 WHERE sale_amount > (SELECT avg_sales FROM sales.t0043);
run;

data sales.t0047;
	merge sales.t0027(in=a) sales.t0017(in=b);
by sale_month;
run;

data sales.t0048;
	set sales.t0011;
	if sale_amount > 100;
run;

PROC SQL;
CREATE TABLE sales.t0049 AS
SELECT SUM(sale_amount) AS total_sales FROM sales.t0016;
run;

PROC SQL;
CREATE TABLE sales.t0050 AS
SELECT AVG(sale_amount) AS avg_sales FROM sales.t0013;
run;

proc print data=sales.t0050; title 't0050'; run;

PROC SQL;
CREATE TABLE sales.t0051 AS
SELECT MONTH(DATE) AS sale_month, SUM(sale_amount) AS total_monthly_sales FROM sales.t0049 GROUP BY MONTH(DATE);
run;

PROC SQL;
CREATE TABLE sales.t0052 AS
SELECT * FROM sales.t0026 WHERE sale_amount > (SELECT avg_sales FROM sales.t0031);
run;

data sales.t0053;
	merge sales.t0046(in=a) sales.t0052(in=b);
by sale_month;
run;

data sales.t0054;
	set sales.t0027;
	if sale_amount > 150;
run;

PROC SQL;
CREATE TABLE sales.t0055 AS
SELECT SUM(sale_amount) AS total_sales FROM sales.t0051;
run;

PROC SQL;
CREATE TABLE sales.t0056 AS
SELECT AVG(sale_amount) AS avg_sales FROM sales.t0038;
run;

PROC SQL;
CREATE TABLE sales.t0057 AS
SELECT MONTH(DATE) AS sale_month, SUM(sale_amount) AS total_monthly_sales FROM sales.t0038 GROUP BY MONTH(DATE);
run;

PROC SQL;
CREATE TABLE sales.t0058 AS
SELECT * FROM sales.t0047 WHERE sale_amount > (SELECT avg_sales FROM sales.t0018);
run;

data sales.t0059;
	merge sales.t0026(in=a) sales.t0049(in=b);
by sale_month;
run;

data sales.t0060;
	set sales.t0032;
	if sale_amount > 150;
run;

proc print data=sales.t0060; title 't0060'; run;

PROC SQL;
CREATE TABLE sales.t0061 AS
SELECT SUM(sale_amount) AS total_sales FROM sales.t0028;
run;

PROC SQL;
CREATE TABLE sales.t0062 AS
SELECT AVG(sale_amount) AS avg_sales FROM sales.t0060;
run;

PROC SQL;
CREATE TABLE sales.t0063 AS
SELECT MONTH(DATE) AS sale_month, SUM(sale_amount) AS total_monthly_sales FROM sales.t0036 GROUP BY MONTH(DATE);
run;

PROC SQL;
CREATE TABLE sales.t0064 AS
SELECT * FROM sales.t0026 WHERE sale_amount > (SELECT avg_sales FROM sales.t0048);
run;

data sales.t0065;
	merge sales.t0031(in=a) sales.t0050(in=b);
by sale_month;
run;

data sales.t0066;
	set sales.t0035;
	if sale_amount > 150;
run;

PROC SQL;
CREATE TABLE sales.t0067 AS
SELECT SUM(sale_amount) AS total_sales FROM sales.t0057;
run;

PROC SQL;
CREATE TABLE sales.t0068 AS
SELECT AVG(sale_amount) AS avg_sales FROM sales.t0062;
run;

PROC SQL;
CREATE TABLE sales.t0069 AS
SELECT MONTH(DATE) AS sale_month, SUM(sale_amount) AS total_monthly_sales FROM sales.t0031 GROUP BY MONTH(DATE);
run;

PROC SQL;
CREATE TABLE sales.t0070 AS
SELECT * FROM sales.t0058 WHERE sale_amount > (SELECT avg_sales FROM sales.t0040);
run;

proc print data=sales.t0070; title 't0070'; run;

data sales.t0071;
	merge sales.t0034(in=a) sales.t0061(in=b);
by sale_month;
run;

data sales.t0072;
	set sales.t0035;
	if sale_amount > 50;
run;

PROC SQL;
CREATE TABLE sales.t0073 AS
SELECT SUM(sale_amount) AS total_sales FROM sales.t0048;
run;

PROC SQL;
CREATE TABLE sales.t0074 AS
SELECT AVG(sale_amount) AS avg_sales FROM sales.t0044;
run;

PROC SQL;
CREATE TABLE sales.t0075 AS
SELECT MONTH(DATE) AS sale_month, SUM(sale_amount) AS total_monthly_sales FROM sales.t0041 GROUP BY MONTH(DATE);
run;

PROC SQL;
CREATE TABLE sales.t0076 AS
SELECT * FROM sales.t0038 WHERE sale_amount > (SELECT avg_sales FROM sales.t0044);
run;

data sales.t0077;
	merge sales.t0050(in=a) sales.t0042(in=b);
by sale_month;
run;

data sales.t0078;
	set sales.t0045;
	if sale_amount > 100;
run;

PROC SQL;
CREATE TABLE sales.t0079 AS
SELECT SUM(sale_amount) AS total_sales FROM sales.t0043;
run;

PROC SQL;
CREATE TABLE sales.t0080 AS
SELECT AVG(sale_amount) AS avg_sales FROM sales.t0065;
run;

proc print data=sales.t0080; title 't0080'; run;

PROC SQL;
CREATE TABLE sales.t0081 AS
SELECT MONTH(DATE) AS sale_month, SUM(sale_amount) AS total_monthly_sales FROM sales.t0043 GROUP BY MONTH(DATE);
run;

PROC SQL;
CREATE TABLE sales.t0082 AS
SELECT * FROM sales.t0076 WHERE sale_amount > (SELECT avg_sales FROM sales.t0069);
run;

data sales.t0083;
	merge sales.t0073(in=a) sales.t0071(in=b);
by sale_month;
run;

data sales.t0084;
	set sales.t0065;
	if sale_amount > 150;
run;

PROC SQL;
CREATE TABLE sales.t0085 AS
SELECT SUM(sale_amount) AS total_sales FROM sales.t0074;
run;

PROC SQL;
CREATE TABLE sales.t0086 AS
SELECT AVG(sale_amount) AS avg_sales FROM sales.t0079;
run;

PROC SQL;
CREATE TABLE sales.t0087 AS
SELECT MONTH(DATE) AS sale_month, SUM(sale_amount) AS total_monthly_sales FROM sales.t0059 GROUP BY MONTH(DATE);
run;

PROC SQL;
CREATE TABLE sales.t0088 AS
SELECT * FROM sales.t0086 WHERE sale_amount > (SELECT avg_sales FROM sales.t0085);
run;

data sales.t0089;
	merge sales.t0065(in=a) sales.t0075(in=b);
by sale_month;
run;

data sales.t0090;
	set sales.t0059;
	if sale_amount > 50;
run;

