"""pipeline.codegen.common — shared Phase-D machinery (language-blind).

Why this file exists: every language's <lang>_pyspark.py generator needs
the same handful of things that have nothing to do with what a term
MEANS — a schema-type name map, a StructType code-builder, the program
header/footer boilerplate, the layout-law output paths, and the
subprocess runner that actually executes a generated script under the
project .venv. None of that is a term->PySpark mapping decision, so it
lives here once instead of being duplicated (or, worse, cross-branched
on language) inside pig_pyspark.py / hive_pyspark.py.

Layout law (Phase-D contract, reproduced here since every path helper in
this file exists only to implement it):
    generated code        -> out/pyspark/<lang>/<stem>.py
    PySpark run outputs   -> out/pyspark_out/<lang>/<stem>/<output_name>/ (CSV)
    Hive reference outputs-> out/hive_ref/<stem>/<output_name>.csv
    DataMatch verdicts    -> reports/e2e_status.json + reports/datamatch.html
    every run appends to  -> logs/run_<lang>_<stem>.log
"""
import os
import subprocess
import time
from pathlib import Path

from pipeline.comments import render as render_comment

REPO_ROOT = Path(__file__).resolve().parents[2]

DEFAULT_VENV_PYTHON = REPO_ROOT / ".venv" / "bin" / "python"

# --------------------------------------------------------------------
# schema types: IR field type atom -> PySpark type constructor name.
# One shared table for every language's LOAD/CREATE TABLE schema, since
# a schema-type name is not a term-shape decision — it's a vocabulary
# mapping, same rules regardless of which DSL printed the atom.

TYPE_MAP = {
    "int": "IntegerType",
    "integer": "IntegerType",
    "long": "LongType",
    "bigint": "LongType",
    "double": "DoubleType",
    "float": "FloatType",
    "chararray": "StringType",
    "string": "StringType",
    "varchar": "StringType",
    "boolean": "BooleanType",
    "bool": "BooleanType",
}

# The fixed set of pyspark.sql.types names imported by every generated
# program, regardless of which ones a given schema actually uses — an
# unused import is harmless and keeps the header identical (and thus
# deterministic) across every generated file.
TYPES_IMPORT_LINE = (
    "from pyspark.sql.types import (\n"
    "    StructType, StructField,\n"
    "    IntegerType, LongType, DoubleType, FloatType, StringType, BooleanType,\n"
    ")"
)


def pyspark_type_name(ir_type):
    """IR schema-type atom (e.g. 'chararray') -> PySpark type constructor
    name (e.g. 'StringType'). Raises KeyError with the offending atom
    named, on purpose — an unmapped type must fail loudly, never emit
    silently-wrong generated code."""
    try:
        return TYPE_MAP[ir_type]
    except KeyError:
        raise KeyError(f"pipeline.codegen.common: no PySpark type mapped for IR type {ir_type!r}")


def struct_field_code(name, ir_type, nullable=True):
    """One StructField(...) source snippet for schema field `name`."""
    pytype = pyspark_type_name(ir_type)
    return f'StructField("{name}", {pytype}(), {nullable})'


def schema_code(fields):
    """fields: list of ('field', name, ir_type) tuples (as parsed by
    pipeline.term_parse from a LOAD's field(name,type) list). Returns a
    single-line `StructType([...])` source expression."""
    parts = [struct_field_code(name, ir_type) for (_functor, name, ir_type) in fields]
    return "StructType([" + ", ".join(parts) + "])"


# --------------------------------------------------------------------
# program scaffolding

def program_header(stem):
    """Lines shared by every generated PySpark script: imports, the
    Python-interpreter pin (see below), + a local[1], UI-disabled
    SparkSession bootstrap named after `stem`.

    The interpreter pin exists because Spark launches its Python workers
    with $PYSPARK_PYTHON and, when that is unset, falls back to whatever
    bare `python3` resolves to on PATH — NOT to the interpreter running
    the driver. On macOS that fallback is the system /usr/bin/python3
    (3.9), which cannot even import this pyspark build's worker module,
    so any job that needs a Python worker dies with an unhelpful
    "EOFException ... reading the port number from pyspark.daemon".
    Pinning to sys.executable keeps driver and workers on one
    interpreter and bakes in no machine path. setdefault, not
    assignment, so a cluster submit (Databricks, spark-submit) that has
    already set them deliberately still wins.
    """
    return [
        "# AUTO-GENERATED by pipeline.codegen — DO NOT EDIT BY HAND.",
        "# Generated ONLY from out/ir/*/*.node4.json terms (Phase-D codegen law).",
        "import os",
        "import sys",
        "",
        "from pyspark.sql import SparkSession",
        "from pyspark.sql import functions as F",
        TYPES_IMPORT_LINE,
        "",
        "# Run Spark's Python workers on the SAME interpreter as this driver.",
        "# Unset, Spark falls back to bare `python3` on PATH — the system 3.9",
        "# on macOS — and every Python-worker task fails. setdefault so a",
        "# cluster submit that already pinned these keeps its own choice.",
        'os.environ.setdefault("PYSPARK_PYTHON", sys.executable)',
        'os.environ.setdefault("PYSPARK_DRIVER_PYTHON", sys.executable)',
        "",
        "spark = (",
        "    SparkSession.builder",
        f'    .appName("{stem}")',
        '    .master("local[1]")',
        '    .config("spark.ui.enabled", "false")',
        "    .getOrCreate()",
        ")",
        'spark.sparkContext.setLogLevel("ERROR")',
        "",
    ]


def program_footer():
    return [
        "",
        "spark.stop()",
        "",
    ]


def blockid_header(block_id):
    return f"# blockid: {block_id}"


# --------------------------------------------------------------------
# comment reattachment (2026-08-26, pipeline.comments): a node4 record's
# own "comments" list -> generated-code lines. Language-blind on purpose —
# the same two helpers serve every <lang>_pyspark.py / *_airflow.py
# generator; none of them re-derives placement, they only call these.

def comment_lines(attachments, source_label, *, indent="", positions=("leading", "prologue")):
    """One rendered "# [source_label:line] text" per attachment whose
    `pos` is in `positions` (default: "leading"/"prologue" — the ones
    that get their OWN generated line), each prefixed with `indent`.
    "trailing"/"inline" attachments are NOT included here — see
    with_trailing below, they append to an existing code line instead."""
    return [
        f"{indent}{render_comment(a, source_label)}"
        for a in attachments if a["pos"] in positions
    ]


def with_trailing(line, attachments, source_label):
    """Append every "trailing"/"inline" attachment to `line` as a Python
    trailing comment fragment: `code_line  # [file:N] text`. Multiple
    trailing/inline comments on one statement all land on that SAME last
    generated line, in source order — this is the owner's specifically-
    requested "if we are unable to place it after a new line, still
    attach it" fallback, applied uniformly whether the comment was
    genuinely inline (mid-statement) or just the ordinary end-of-
    statement trailing case."""
    frags = [
        render_comment(a, source_label)
        for a in attachments if a["pos"] in ("trailing", "inline")
    ]
    if not frags:
        return line
    return line + "  " + "  ".join(frags)


def write_program(path, lines):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


# --------------------------------------------------------------------
# layout-law paths

def stem_of(ir_json_path):
    """out/ir/pig/p01_load_filter_store.node4.json -> 'p01_load_filter_store'"""
    name = Path(ir_json_path).name
    for suffix in (".node4.json", ".json"):
        if name.endswith(suffix):
            return name[: -len(suffix)]
    return Path(ir_json_path).stem


def generated_script_path(lang, stem, repo_root=REPO_ROOT):
    return Path(repo_root) / "out" / "pyspark" / lang / f"{stem}.py"


def pyspark_out_dir(lang, stem, output_name, repo_root=REPO_ROOT):
    """Absolute on-disk location of one converted output — for harness code
    that has to touch the directory (tests, cleanup, DataMatch probing)."""
    return Path(repo_root) / "out" / "pyspark_out" / lang / stem / output_name


def pyspark_out_rel(lang, stem, output_name):
    """The SAME layout-law path, repo-root-relative — this is the form that
    gets baked into generated source. Generated programs always run with
    cwd = repo root (see run_generated below), and every input path the
    generators emit is already relative, so writing the output path
    relative too keeps a generated file byte-identical on every machine:
    portable, reviewable in a diff, and runnable unchanged on a cluster
    where the absolute developer path does not exist."""
    return Path("out") / "pyspark_out" / lang / stem / output_name


def log_path(lang, stem, repo_root=REPO_ROOT):
    return Path(repo_root) / "logs" / f"run_{lang}_{stem}.log"


# --------------------------------------------------------------------
# runner: execute one generated script under the project .venv

def run_generated(lang, stem, *, venv_python=None, repo_root=REPO_ROOT, timeout=600):
    """Run out/pyspark/<lang>/<stem>.py with the project .venv's python,
    cwd = repo_root (so the relative corpus/... and out/... paths baked
    into the generated script resolve), appending a timestamped record
    to logs/run_<lang>_<stem>.log. Returns a dict:
        {stem, lang, ok, returncode, duration_s, script, stdout, stderr}

    PYSPARK_PYTHON/PYSPARK_DRIVER_PYTHON are FORCED to `venv_python` in
    the child's environment — overwriting any inherited value, unlike
    the setdefault the generated script itself carries. Picking the
    driver interpreter is this function's whole job, and Spark's Python
    workers have to be that same interpreter or they cannot unpickle
    what the driver sends. A stale PYSPARK_PYTHON exported in the
    operator's shell would otherwise silently point the workers at a
    different Python than the one named on the command line here.
    """
    venv_python = Path(venv_python) if venv_python else DEFAULT_VENV_PYTHON
    script = generated_script_path(lang, stem, repo_root=repo_root)
    log_file = log_path(lang, stem, repo_root=repo_root)
    log_file.parent.mkdir(parents=True, exist_ok=True)

    if not script.is_file():
        raise FileNotFoundError(f"run_generated: no generated script at {script}")

    env = dict(os.environ)
    env["PYSPARK_PYTHON"] = str(venv_python)
    env["PYSPARK_DRIVER_PYTHON"] = str(venv_python)

    start = time.time()
    proc = subprocess.run(
        [str(venv_python), str(script)],
        cwd=str(repo_root),
        capture_output=True,
        text=True,
        timeout=timeout,
        env=env,
    )
    duration = time.time() - start
    ok = proc.returncode == 0

    with open(log_file, "a", encoding="utf-8") as f:
        f.write(f"\n===== run {time.strftime('%Y-%m-%d %H:%M:%S')} stem={stem} lang={lang} =====\n")
        f.write(f"cmd: {venv_python} {script}\n")
        f.write(f"returncode: {proc.returncode}  duration_s: {duration:.2f}\n")
        f.write("--- stdout ---\n")
        f.write(proc.stdout)
        f.write("\n--- stderr ---\n")
        f.write(proc.stderr)
        f.write("\n")

    return {
        "stem": stem,
        "lang": lang,
        "ok": ok,
        "returncode": proc.returncode,
        "duration_s": duration,
        "script": str(script),
        "log": str(log_file),
        "stdout": proc.stdout,
        "stderr": proc.stderr,
    }
