"""exp_42 2026-09-08 — generate a big SAS program for Bench scalability tests.

Shapes are the ones test_vishnu_testdata.sas already uses (so the grammar and the
rules cover them): one DATA step with DATALINES, DATA steps with SET + IF, PROC SQL
CREATE TABLE ... AS SELECT with SUM / AVG / WHERE / GROUP BY, a MERGE ... BY, and a
PROC PRINT for every tenth table. Every block reads one or two earlier tables, so the
lineage is a DAG with fan-in, not a chain.

Usage:  python3 testdata/gen_big.py 1000 > corpus/sas/big_1000.sas
"""
import random
import sys

n = int(sys.argv[1]) if len(sys.argv) > 1 else 1000
random.seed(n)
out = []
w = out.append

w("/* big_%d.sas — generated by testdata/gen_big.py for Bench performance tests */" % n)
w("libname sales 'C:\\SASData\\Sales';")
w("")
w("data sales.sales_data;")
w("input sale_id $ sale_amount date :mmddyy10.;")
w("format date mmddyy10.;")
w("datalines;")
for i in range(1, 23):
    w("%03d %d %02d/%02d/2023" % (i, random.choice([0, 50, 75, 130, 150, 199.99, 300]), (i % 12) + 1, (i % 27) + 1))
w(";")
w("run;")
w("")

tables = ["sales_data"]          # every generated block reads from earlier tables
made = 1                          # blocks so far (libname + sales_data = 2, but count tables)
k = 0
while made < n - 1:
    k += 1
    name = "t%04d" % k
    src = random.choice(tables[-40:])           # recent tables: a deep graph, not a star
    shape = k % 6
    if shape == 0:
        w("data sales.%s;" % name)
        w("\tset sales.%s;" % src)
        w("\tif sale_amount > %d;" % random.choice([50, 100, 150]))
        w("run;")
    elif shape == 1:
        w("PROC SQL;")
        w("CREATE TABLE sales.%s AS" % name)
        w("SELECT SUM(sale_amount) AS total_sales FROM sales.%s;" % src)
        w("run;")
    elif shape == 2:
        w("PROC SQL;")
        w("CREATE TABLE sales.%s AS" % name)
        w("SELECT AVG(sale_amount) AS avg_sales FROM sales.%s;" % src)
        w("run;")
    elif shape == 3:
        w("PROC SQL;")
        w("CREATE TABLE sales.%s AS" % name)
        w("SELECT MONTH(DATE) AS sale_month, SUM(sale_amount) AS total_monthly_sales FROM sales.%s GROUP BY MONTH(DATE);" % src)
        w("run;")
    elif shape == 4:
        other = random.choice(tables[-40:])
        w("PROC SQL;")
        w("CREATE TABLE sales.%s AS" % name)
        w("SELECT * FROM sales.%s WHERE sale_amount > (SELECT avg_sales FROM sales.%s);" % (src, other))
        w("run;")
    else:
        other = random.choice(tables[-40:])
        w("data sales.%s;" % name)
        w("\tmerge sales.%s(in=a) sales.%s(in=b);" % (src, other))
        w("by sale_month;")
        w("run;")
    w("")
    tables.append(name)
    made += 1
    if k % 10 == 0 and made < n - 1:
        w("proc print data=sales.%s; title '%s'; run;" % (name, name))
        w("")
        made += 1

print("\n".join(out))
